CREATE TABLE Matches (
    match_id INT PRIMARY KEY,
    draw_id INT,
    match_status ENUM('OK', 'Abandoned', 'Suspended') DEFAULT 'OK',
    round_id INT,
    player1_id INT,
    player2_id INT NULL,
    winner_id INT NULL,
    player1_status_id INT,
    player2_status_id INT NULL,
    set1_player1 INT,
    set1_player2 INT,
    set1_player1_tiebreak INT,
    set1_player2_tiebreak INT,
    set2_player1 INT,
    set2_player2 INT,
    set2_player1_tiebreak INT,
    set2_player2_tiebreak INT,
    supertiebreak_player1 INT DEFAULT NULL,
    supertiebreak_player2 INT DEFAULT NULL,
    FOREIGN KEY (draw_id) REFERENCES Draws(draw_id),
    FOREIGN KEY (round_id) REFERENCES MatchRound(round_id),
    FOREIGN KEY (player1_id) REFERENCES Players(player_id),
    FOREIGN KEY (player2_id) REFERENCES Players(player_id),
    FOREIGN KEY (winner_id) REFERENCES Players(player_id),
    FOREIGN KEY (player1_status_id) REFERENCES PlayerStatus(status_id),
    FOREIGN KEY (player2_status_id) REFERENCES PlayerStatus(status_id),
    CHECK (supertiebreak_player1 IS NULL OR supertiebreak_player1 >= 0),
    CHECK (supertiebreak_player2 IS NULL OR supertiebreak_player2 >= 0)
);

